server:
  port: 8084

spring:
  application:
    name: translation-service

  datasource:
    url: jdbc:postgresql://localhost:5432/translation_db
    username: postgres
    password: Satya@2005
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

translation:
  default-language: en
  supported-languages: en,hi,mr